---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarksproducer
  labels:
    app: bookmarksproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarksproducer
  template:
    metadata:
      labels:
        app: bookmarksproducer
    spec:
      containers:
        - name: bookmarksproducer
          image: griga/bookmarksproducer:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bookmarksproducer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bookmarksproducer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: bookmarksproducer
spec:
  rules:
    - host: producer.localhost
      http:
        paths:
          - backend:
              serviceName: bookmarksproducer
              servicePort: 8080
