---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarksconsumer
  labels:
    app: bookmarksconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarksconsumer
  template:
    metadata:
      labels:
        app: bookmarksconsumer
    spec:
      containers:
        - name: bookmarksconsumer
          image: griga/bookmarksconsumer:latest
          ports:
            - containerPort: 8888
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: bookmarksconsumer
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: bookmarksconsumer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: bookmarksconsumer
spec:
  rules:
    - host: consumer.localhost
      http:
        paths:
          - backend:
              serviceName: bookmarksconsumer
              servicePort: 8888
