---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookmarksconsumer
spec:
  serviceName: "bookmarksconsumer"
  replicas: 2
  selector:
    matchLabels:
      app: bookmarksconsumer
  template:
    metadata:
      labels:
        app: bookmarksconsumer
    spec:
      containers:
        - name: bookmarksconsumer2
          image: griga/bookmarksconsumer2:latest
          ports:
            - containerPort: 8888
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: count-store
              mountPath: /data/count-store
  volumeClaimTemplates:
    - metadata:
        name: count-store
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: bookmarksconsumer
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: bookmarksconsumer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: bookmarksconsumer
spec:
  rules:
    - host: consumer.localhost
      http:
        paths:
          - backend:
              serviceName: bookmarksconsumer
              servicePort: 8888
