---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarksproxy
  labels:
    app: bookmarksproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarksproxy
  template:
    metadata:
      labels:
        app: bookmarksproxy
    spec:
      containers:
        - name: bookmarksproxy
          image: griga/bookmarksproxy:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bookmarksproxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bookmarksproxy
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: bookmarksproxy
spec:
  rules:
    - host: proxy.localhost
      http:
        paths:
          - backend:
              serviceName: bookmarksproxy
              servicePort: 8080
