spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-confluent-oss-cp-kafka:9092
#          brokers: localhost:9092
      bindings:
        output:
          destination: bookmarks
          contentType: application/json