spring.application.name: kafkastream
spring.cloud.stream.bindings.reduce-in-0.destination: bookmarks

spring.cloud.stream.kafka.streams.binder:
#  applicationId: ${MY_POD_NAME}
  applicationId: jans-bookmarks-app
#  startOffset: earliest
  brokers: my-confluent-oss-cp-kafka:9092
#  brokers: localhost:9092
  configuration:
    application.server: ${MY_POD_NAME}:8888
#    application.server: localhost:8889
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 1000